### ISSUE TITLE
compability score computed correctly in Python 3.8 ?

### ISSUE THREAD

**Issue by lefi7z** [takluyver/pynsist#212]
Using Python 3.8.2 on 64bit Windows, pynsist insists on an incompability:

```
ValueError: Wheel h5py-2.10.0-cp38-cp38-win_amd64.whl is not compatible with Python 3.8.0, win_amd64
```

As I assume that the compatibility is only deduced from the naming convention, this seems like an error to me. 

---------- stacktrace ------------
Collecting wheel file: h5py-2.10.0-cp38-cp38-win_amd64.whl (from: ../dist/*whl)
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\Scripts\pynsist.exe\__main__.py", line 7, in <module>
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\__init__.py", line 520, in main
    ec = InstallerBuilder(**args).run(makensis=(not options.no_makensis))
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\__init__.py", line 473, in run
    self.prepare_packages()
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\__init__.py", line 347, in prepare_packages
    wg.get_all()
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\wheels.py", line 296, in get_all
    self.get_globs()
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\wheels.py", line 314, in get_globs
    self.validate_wheel(path)
  File "C:\Users\Moritz.Koenemann\AppData\Roaming\Python\Python38\site-packages\nsist\wheels.py", line 335, in validate_wheel
    raise ValueError('Wheel {} is not compatible with Python {}, {}'
ValueError: Wheel h5py-2.10.0-cp38-cp38-win_amd64.whl is not compatible with Python 3.8.0, win_amd64

**Comment by takluyver** [comment]
I think this was coincidentally fixed by PR #210, merged yesterday. I'm planning to do a couple more fixes and do a new release soon.

Coincidentally, I'm also one of the maintainers of h5py. :slightly_smiling_face: :wave:

**Comment by lefi7z** [comment]
looks as if I found just the right person at the right time! ;-)

I had been reading about that PR and saw the opportunity to get this fixed soon. I might do a checkout today and test my case against it. I will let you know if that solved it!

**Comment by lefi7z** [comment]
...oh it's on PyPI already, wonderful!

**Comment by takluyver** [comment]
Yup, I had a bit of spare time yesterday evening, so I thought I'd do that rather than refreshing the news every 10 seconds. :wink:

**Comment by lefi7z** [comment]
Alright, the issue is solved, thanks a lot! 

Yeah, I've been continuously listening to the radio from Austria. You get a news update every half hour instead of every 10 seconds. And still not much is happening..
