### ISSUE TITLE
Attempting to create installer for Pygame programs results in "ImportError: namespace packages do not have loaders"

### ISSUE THREAD

**Issue by asweigart** [takluyver/pynsist#45]
In my fork I've added a couple new Pygame program examples. One needs to include a freesansbold.ttf file, the other has no other requirements other than the pygame module.

This error comes up running on Windows 7 with Python 3.3.5 32 bit.

Here're the tracebacks (both have the same error):

C:\github\inventwithpythondotcom\static>"C:\python34\python.exe" "C:\Python34\Scripts\\pynsist" memorypuzzle_installer.cfg
Python MSI already in build directory.
Copying packages into build directory...
Traceback (most recent call last):
  File "C:\Python34\Scripts\\pynsist", line 3, in <module>
    main()
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 414, in main
    ).run(makensis=(not options.no_makensis))
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 356, in run
    self.prepare_packages()
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 262, in prepare_packages
    py_version=self.py_version, exclude=self.exclude)
  File "C:\python34\lib\site-packages\nsist\copymodules.py", line 224, in copy_modules
    mc.copy(modname, target, exclude)
  File "C:\python34\lib\site-packages\nsist\copymodules.py", line 113, in copy
    loader = importlib.find_loader(modname, self.path)
  File "C:\python34\lib\importlib\__init__.py", line 82, in find_loader
    name=name)
ImportError: namespace packages do not have loaders

C:\github\inventwithpythondotcom\static>"C:\python34\python.exe" "C:\Python34\Scripts\\pynsist" wormy_installer.cfg
Python MSI already in build directory.
Copying packages into build directory...
Traceback (most recent call last):
  File "C:\Python34\Scripts\\pynsist", line 3, in <module>
    main()
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 414, in main
    ).run(makensis=(not options.no_makensis))
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 356, in run
    self.prepare_packages()
  File "C:\python34\lib\site-packages\nsist\__init__.py", line 262, in prepare_packages
    py_version=self.py_version, exclude=self.exclude)
  File "C:\python34\lib\site-packages\nsist\copymodules.py", line 224, in copy_modules
    mc.copy(modname, target, exclude)
  File "C:\python34\lib\site-packages\nsist\copymodules.py", line 113, in copy
    loader = importlib.find_loader(modname, self.path)
  File "C:\python34\lib\importlib\__init__.py", line 82, in find_loader
    name=name)
ImportError: namespace packages do not have loaders

**Comment by asweigart** [comment]
Nix this. I think this was because I was using another version of Python to run pynsist other than the one listed in the installer. Actually, couldn't we make the "version" key under [Python] optional and have it default to the version of Python running the script?

I'll probably file a PR that will add checks for the problem I encountered. But Pynsist itself seems to be working just fine.

**Comment by takluyver** [comment]
It should, I think, be OK to run it with one Python version and target another one - though it should complain if it tries to copy an extension module from your system, because of the likely ABI mismatch. That error suggests that it doesn't handle namespace packages correctly, which is entirely possible.
