### ISSUE TITLE
Application doesn't launch after installed

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#72]
I used the PyQt5 example to create a config.

https://github.com/Siecje/qml-testing/tree/pynsist

I'm able to create the installer. But the application doesn't launch after it is installed.

**Comment by takluyver** [comment]
There should be a log file in `%APPDATA%` where it has recorded any errors that occurred when it failed to start. That's the best place to start debugging.

http://pynsist.readthedocs.io/en/latest/installers.html#uncaught-exceptions

**Comment by Siecje** [comment]
The file is created but it is empty.

If I use python to run the .pyw I get errors that 
```
cody@COMP MINGW64 /c/Program Files/QMLApplication2
$ python QMLApplication.launch.pyw
QQmlApplicationEngine failed to load component
file:///C:/Program Files/QMLApplication2/pkgs/qmlapp/Main.qml:2 module "QtQuick.Controls" is not installed
file:///C:/Program Files/QMLApplication2/pkgs/qmlapp/Main.qml:1 module "QtQuick" is not installed
file:///C:/Program Files/QMLApplication2/pkgs/qmlapp/Main.qml:2 module "QtQuick.Controls" is not installed
file:///C:/Program Files/QMLApplication2/pkgs/qmlapp/Main.qml:1 module "QtQuick" is not installed
```

**Comment by takluyver** [comment]
Aha, so it doesn't know where to look for the QML files shipped with PyQt5. They are in the wheel, so they should be getting bundled into your application, but I guess you need to tell it where to look.

A bit of searching turned up [this SO answer](http://stackoverflow.com/a/37845134/434217), saying there's an environment variable called `QML2_IMPORT_PATH`. In your code, try setting that before you load any Qml stuff - you'll need to calculate the value you need after installation, but it should end like:

```
...application_dir\pkgs\PyQt5\Qt\qml
```

**Comment by Siecje** [comment]
I don't have the final ```qml``` directory in the ```build/``` dir or the installation dir.

I tried setting the full path in case it might be discovered and added to the build and installer or because I am installing it on the same machine so it should find it at runtime.

However I'm getting an error that I have seen before when I was editing the files that were installed in Program Files while trying to debug.

```Python
Traceback (most recent call last):
  File "QMLApplication.launch.pyw", line 30, in <module>
    from qmlapp import Main
  File "pkgs\qmlapp\__init__.py", line 1, in <module>
    from .main import Main
  File "pkgs\qmlapp\main.py", line 9
    os.environ['QML2_IMPORT_PATH'] = 'C:\Users\cody\Anaconda3\Lib\site-packages\PyQt5\Qt\qml'
                                    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by Siecje** [comment]
I replaced the above line with 

```Python
os.environ['QML2_IMPORT_PATH'] = os.path.join('C', 'Users', 'cody', 'Anaconda3', 'Lib', 'site-packages', 'PyQt5', 'Qt', 'qml')
```

And I get the same errors about missing ```QtQuick.Controls```

**Comment by takluyver** [comment]
To put a path using backslashes into Python, you need to double them up, like `'C:\\Users``. It's because there's a way of typing a unicode character like `\U00F14A67`.

I'm going to clone your repo and see what gets into the build directory...

**Comment by takluyver** [comment]
Aha, it looks like the qml directory wasn't in the wheels for PyQt5 5.6, but it was included in 5.7. Try changing the version number in your `installer.cfg` file and rebuilding the installer.

Try first without setting the environment variable again, and if it's still the same error, we'll try to work out where it belongs.

**Comment by Siecje** [comment]
I changed the version to 5.7 but now I'm getting a different error.

```Python
$ pip freeze | grep PyQt
PyQt5==5.7
```

```
$ pynsist.exe installer.cfg
Unpacking Python...
Copying packages into build directory...
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cody\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cody\Anaconda3\Scripts\pynsist.exe\__main__.py", line 9, in <module>
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 523, in main
    ).run(makensis=(not options.no_makensis))
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 461, in run
    self.prepare_packages()
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 342, in prepare_packages
    py_version=self.py_version, bitness=self.py_bitness)
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 150, in fetch_pypi_wheels
    whl_file = wd.fetch()
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 101, in fetch
    p = self.check_cache()
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 95, in check_cache
    for p in release_dir.iterdir())
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 57, in pick_best_wheel
    for release in release_list:
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 94, in <genexpr>
    rel = self.pick_best_wheel(CachedRelease(p.name)
  File "c:\users\cody\anaconda3\lib\pathlib.py", line 1049, in iterdir
    for name in self._accessor.listdir(self):
  File "c:\users\cody\anaconda3\lib\pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\cody\\AppData\\Local\\pynsist\\pypi\\PyQt5\\5.7'
```

```C:\Users\cody\AppData\Local\pynsist\pypi\PyQt5\5.6``` does exist.

**Comment by Siecje** [comment]
I manually downloaded the 5.7 wheel and put it in ```C:\Users\cody\AppData\Local\pynsist\pypi\PyQt5\5.7\```

```shell
$ cat installer.cfg
[Application]
name=QMLApplication
version=1.0
entry_point=qmlapp:Main

[Python]
version=3.5.2
bitness=64
format=bundled

[Include]
packages=qmlapp
pypi_wheels =
    PyQt5==5.7
    sip==4.18

$ pynsist.exe installer.cfg
Unpacking Python...
Copying packages into build directory...
Traceback (most recent call last):
  File "c:\users\cody\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cody\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cody\Anaconda3\Scripts\pynsist.exe\__main__.py", line 9, in <module>
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 523, in main
    ).run(makensis=(not options.no_makensis))
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 461, in run
    self.prepare_packages()
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\__init__.py", line 342, in prepare_packages
    py_version=self.py_version, bitness=self.py_bitness)
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 149, in fetch_pypi_wheels
    wd = WheelDownloader(req, py_version, bitness)
  File "c:\users\cody\anaconda3\lib\site-packages\nsist\pypi.py", line 31, in __init__
    raise ValueError("Requirement {!r} did not match name==version")
ValueError: Requirement {!r} did not match name==version
```

**Comment by takluyver** [comment]
The first error you saw when it tried to download the wheel was fixed just the other day (#74). Once we've worked out any changes needed here, I'll do a new release.

Try putting `PyQt5==5.7` on the same line after `pypi_wheels = `.

**Comment by Siecje** [comment]
It works! 

It needed to be on the same line.

Thanks so much for your help!

**Comment by takluyver** [comment]
The QML stuff worked as well? Awesome :-)

Would you like to update the example in this repository to do something simple with QML, just to demonstrate that it works? It's currently just a straight copy of the PyQt4 example.
