### ISSUE TITLE
Fail to fetch PyQt 5.7 if 5.6 exists in cache folder

### ISSUE THREAD

**Issue by cachitas** [takluyver/pynsist#74]
With PyQt 5.6 in cache I got this error:

```
$ pynsist installer.cfg 
Copying Python installer to build directory
Copying packages into build directory...
Traceback (most recent call last):
  File "/home/hugo/.virtualenvs/flytracker-postproc/bin/pynsist", line 11, in <module>
    sys.exit(main())
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/__init__.py", line 523, in main
    ).run(makensis=(not options.no_makensis))
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/__init__.py", line 461, in run
    self.prepare_packages()
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/__init__.py", line 342, in prepare_packages
    py_version=self.py_version, bitness=self.py_bitness)
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/pypi.py", line 150, in fetch_pypi_wheels
    whl_file = wd.fetch()
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/pypi.py", line 101, in fetch
    p = self.check_cache()
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/pypi.py", line 95, in check_cache
    for p in release_dir.iterdir())
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/pypi.py", line 57, in pick_best_wheel
    for release in release_list:
  File "/home/hugo/.virtualenvs/flytracker-postproc/lib/python3.5/site-packages/nsist/pypi.py", line 94, in <genexpr>
    rel = self.pick_best_wheel(CachedRelease(p.name)
  File "/usr/lib/python3.5/pathlib.py", line 1049, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/hugo/.cache/pynsist/pypi/PyQt5/5.7'
```

Removing it and trying again, pynsist fetched the 5.7.

**Comment by takluyver** [comment]
Thanks for the heads up, I guess there's just a case I've missed when checking for and creating directories.
